name: Jekyll site CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    
    - name: Install dependencies
      run: bundle install
    
    - name: Build with Jekyll
      run: bundle exec jekyll build --baseurl "${{ github.event.repository.name }}"
    
    - name: Test
      run: bundle exec jekyll doctor
